### ISSUE TITLE
The command was unsuccessful.

### ISSUE THREAD

**Issue by ming020617** [gbonacini/sigenmax2870#1]
Hi, I'm having some problems running this program as shown here. Do you have any good solution for this, thanks!
![1710835003669](https://github.com/gbonacini/sigenmax2870/assets/163368386/c95360d1-d5d3-4af9-9263-dcaa933df4f7)

**Comment by ming020617** [comment]
After changing the path and running the command successfully, I really appreciate the author's free help, and I offer my most sincere thanks to you!

**Comment by gbonacini** [comment]
Note: 

> After changing the path and running the command successfully, I really appreciate the author's free help, and I offer my most sincere thanks to you!

To benefit everyone:
* if the library libsigenmax2870.so.1 is not found, you have to add the path in which it is installed (i.e. /usr/local/lib , see make install output or use command like "find" to verify) in LD_LIBRAY_PATH environmental variable or in system config file ( see Linux documentation for further information );
* prepending "./" to the command is not required if the program is installed properly and the executable is in PATH environmental variable;
* I'm adding some notes in README for easy lookup in case of troubleshooting.
